name: Déploiement FTP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Déploiement FTP vers LWS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.a2cmieux.fr
          username: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_SECRET }}
          local-dir: ./site/
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
